config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  resources :users, only: [:new, :show, :create]

  # sessions resource should be singular?
  resource :session, only: [:new, :create, :destroy]
  root to: redirect("/cats")
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :cats,
  foreign_key: :user_id,
  class_name: :Cat

  has_many :cat_rental_requests
  has_many :session_tokens

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
  end

  def show
    @user = current_user
    render :show
  end

  def create
    user = User.new(user_params)
    if user.save
      msg = UserMailer.welcome_email(user)
      msg.deliver
      login_user(user)
    else
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>SIGN UP </h1>

<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="text" name="user[username]" value="">username
  <input type="text" name="user[password]" value="">password
  <input type="submit" value="submit">
</form>

<br>

<%= link_to "Back to index", cats_url %>

<% content_for :footer do %>
  <p>
    You know you want to sign up.
  </p>
<% end %>

app/views/users/show.html.erb
<h1>HI <%= @user.username %>!</h1>
<ul>
  <% @user.session_tokens.each do |token| %>
    <li>you're logged in here: <%= token.client %></li>
    <% end %>
</ul>

<%= link_to "go to cats index", cats_url %>

<% content_for :footer do %>
  <p>
    This is all about you.
  </p>
<% end %>